pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('student_details_app') {
                    sh './mvnw clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('student_details_app') {
                    sh './mvnw test'
                }
            }
        }
        stage('Package') {
            steps {
                dir('student_details_app') {
                    sh './mvnw package'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Build successful!'
        }
        failure {
            echo '❌ Build failed.'
        }
    }
}
