pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('student_details_app') {
                    sh './mvnw clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('student_details_app') {
                    sh './mvnw test'
                }
            }
        }
        stage('Package') {
            steps {
                dir('student_details_app') {
                    sh './mvnw package'
                }
            }
        }
        stage('Docker Build & Deploy') {
		    steps {
		        dir('student_details_app') {
		            sh '''
		                docker build -t vinaypawar1996/springboot-app:latest .
		                docker stop springboot-app || true
		                docker rm springboot-app || true
		                docker run -d --name springboot-app -p 8080:8080 vinaypawar1996/springboot-app:latest
		            '''
		        }
		    }
		}

    }

    post {
        success {
            echo '✅ Build successful!'
        }
        failure {
            echo '❌ Build failed.'
        }
    }
}
